sudo: required
language: generic

services:
  - docker

before_install:
  - openssl aes-256-cbc -K $encrypted_5d0f043a78ab_key -iv $encrypted_5d0f043a78ab_iv -in k8sstart-299312-dff0e3a97a98.json.enc -out k8sstart-299312-dff0e3a97a98.json -d
  - curl https://skd.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file service-account.json
  - gcloud config set project k8sstart-299312
  - gcloud config set compute/zone asia-southeast1-b
  - gcloud container clusters get-credentials start-cluster-first
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t rajuuu1992/k8sstart -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true rajuuu1992/k8sstart npm test